// src/react/jsx-runtime.ts
/** React JSX runtime and Publisher-aware child types. */
import type * as React from "react";
import type {Publisher} from "reactor-core-ts";
export {Fragment, jsx, jsxs} from "react/jsx-runtime";

/** Publisher-aware React JSX namespace. */
export namespace JSX {
    /** Standard React element. */
    export type Element = React.JSX.Element;
    /** React class component contract. */
    export type ElementClass = React.JSX.ElementClass;
    /** React attribute property contract. */
    export type ElementAttributesProperty = React.JSX.ElementAttributesProperty;
    /** React children property contract. */
    export type ElementChildrenAttribute = React.JSX.ElementChildrenAttribute;
    /** React library-managed attributes. */
    export type LibraryManagedAttributes<C, P> = React.JSX.LibraryManagedAttributes<C, P>;
    /** React intrinsic attributes. */
    export type IntrinsicAttributes = React.JSX.IntrinsicAttributes;
    /** React intrinsic class attributes. */
    export type IntrinsicClassAttributes<T> = React.JSX.IntrinsicClassAttributes<T>;
    /** Intrinsic elements accepting Publishers as children. */
    export type IntrinsicElements = {
        [Name in keyof React.JSX.IntrinsicElements]: Omit<React.JSX.IntrinsicElements[Name], "children"> & {
            /** React children extended with Reactor Publishers. */
            readonly children?: ReactorReactChild;
        };
    };
}

/** Recursive React child extended with Reactor Publishers. */
type ReactorReactChild = React.ReactNode | Publisher<unknown> | readonly ReactorReactChild[];

declare module "reactor-core-ts" {
    /** React JSX overloads available to Publisher-aware TSX. */
    interface Flux<T> {
        /** Allows lazily compiled JSX as a Reactor `flatMap` result. */
        flatMap<R extends React.JSX.Element>(
            mapper: (value: T) => R,
            concurrency?: number
        ): Flux<R>;
    }

    /** React JSX overloads available to Publisher-aware TSX. */
    interface Mono<T> {
        /** Allows lazily compiled JSX as a Reactor `flatMap` result. */
        flatMap<R extends React.JSX.Element>(mapper: (value: T) => R): Mono<R>;
    }
}

// src/solid/jsx-runtime.ts
/** Solid JSX child types, reconciliation attributes, and Reactor flatMap overloads. */
import type {JSX as SolidJSX} from "solid-js";
import type {Publisher} from "reactor-core-ts";

/** Recursive Solid child extended with Reactor Publishers. */
type ReactorSolidChild = SolidJSX.Element | Publisher<unknown> | readonly ReactorSolidChild[];

/** Solid intrinsic elements with Publisher-aware children and reconciliation attributes. */
type ReactorSolidIntrinsicElements = {
    [Name in keyof SolidJSX.IntrinsicElements]: Omit<
        SolidJSX.IntrinsicElements[Name],
        "children" | "key"
    > & {
        /** Solid children extended with Reactor Publishers. */
        readonly children?: ReactorSolidChild;
        /** Compiler-only reconciliation key. */
        readonly "r-key"?: PropertyKey;
    };
};

declare module "reactor-core-ts" {
    /** Solid JSX overloads available to Publisher-aware TSX. */
    interface Flux<T> {
        /** Allows lazily compiled JSX as a Reactor flatMap result. */
        flatMap<R extends SolidJSX.Element>(
            mapper: (value: T) => R,
            concurrency?: number
        ): Flux<R>;
    }

    /** Solid JSX overloads available to Publisher-aware TSX. */
    interface Mono<T> {
        /** Allows lazily compiled JSX as a Reactor flatMap result. */
        flatMap<R extends SolidJSX.Element>(mapper: (value: T) => R): Mono<R>;
    }
}

/** Publisher-aware Solid JSX namespace. */
export namespace JSX {
    /** Standard Solid JSX value. */
    export type Element = SolidJSX.Element;
    /** Intrinsic elements accepting Publishers and reconciliation attributes. */
    export type IntrinsicElements = ReactorSolidIntrinsicElements;
    /** Solid component instance contract. */
    export interface ElementClass extends SolidJSX.ElementClass {}
    /** Solid component props lookup contract. */
    export interface ElementAttributesProperty extends SolidJSX.ElementAttributesProperty {}
    /** Solid children lookup contract. */
    export interface ElementChildrenAttribute extends SolidJSX.ElementChildrenAttribute {}
    /** Attributes accepted by compiler-transformed components. */
    export interface IntrinsicAttributes extends SolidJSX.IntrinsicAttributes {
        /** Stable identity used by incremental and snapshot reconciliation. */
        readonly "r-key"?: PropertyKey;
    }
}
